using Agrafarm.DTO;
using Agrafarm.Model;
using AutoMapper;
using System.Linq;

namespace Agrafarm.AutoMapProfile
{
    public class MappingProfile : Profile
    {
        public MappingProfile()
        {
            // ✅ Product → ProductDto mapping
            CreateMap<Product, ProductDto>()
                .ForMember(dest => dest.ImageUrls, opt => opt.MapFrom(src => src.Images.Select(i => i.ImageUrl)));

            // ✅ ProductDto → Product mapping (optional reverse)
            CreateMap<ProductDto, Product>();

            // ✅ ProductCreateDto → Product mapping
            CreateMap<ProductCreateDto, Product>()
                .ForMember(dest => dest.Id, opt => opt.Ignore())          // id generated by DB
                .ForMember(dest => dest.Images, opt => opt.Ignore());     // we handle image mapping manually

            // ✅ User and Category mappings
            CreateMap<User, UserRegisterDto>().ReverseMap();
            CreateMap<Category, CategoryDto>().ReverseMap();
        }
    }
}
